# Generated by Django 2.0.3 on 2018-03-24 14:57

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0002_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeframe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carpool',
            name='days',
        ),
        migrations.AddField(
            model_name='membership',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wen', 'Wendsday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturady'), ('sun', 'Sunday')], default=[], max_length=27),
        ),
        migrations.AddField(
            model_name='membership',
            name='tripABegin',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='membership',
            name='tripAEnd',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
        migrations.AddField(
            model_name='membership',
            name='tripBBegin',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='membership',
            name='tripBEnd',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.DeleteModel(
            name='Timeframe',
        ),
    ]
