# Generated by Django 2.0.3 on 2018-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0003_auto_20180324_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('MI', 'Mini Car'), ('SP', 'Sports Car'), ('SE', 'Sedan'), ('VA', 'Van'), ('SU', 'SUV')], max_length=1)),
            ],
        ),
    ]
