# Generated by Django 2.0.3 on 2018-03-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0005_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kind',
            field=models.CharField(choices=[('MI', 'Mini Car'), ('SP', 'Sports Car'), ('SE', 'Sedan'), ('VA', 'Van'), ('SU', 'SUV')], max_length=2),
        ),
    ]
