# Generated by Django 2.0.3 on 2018-03-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0006_auto_20180324_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
    ]
