# Generated by Django 2.0.3 on 2018-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0007_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
