# Generated by Django 2.0.3 on 2018-03-25 08:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0008_car_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wen', 'Wendsday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturady'), ('sun', 'Sunday')], default=['mon', 'tue', 'wen', 'thu', 'fri'], max_length=27),
        ),
    ]
